### ISSUE TITLE
Enhancement: Volunteer page Inconsistent styling

### ISSUE THREAD

**Issue by nujabes77** [codeforpdx/codepdx_website#119]
### Describe the Current Behavior/Feature:

Update Styling and replacxe "-" with Numbering as displayed in screenshot below

---
<img width="915" alt="Screenshot 2024-02-10 at 2 27 22 PM" src="https://github.com/codeforpdx/codepdx_website/assets/96148888/3f46c591-47d5-43fe-91e9-05b736d60863">

**Comment by andycwilliams** [comment]
I believe it was @xscottxbrownx who wrote these. I can't assume the intention behind choosing hyphens over numbers, but my guess is that it's all intentional. The number ones are sequential steps for people to take, whereas the hyphens just denote specific points that aren't ordered in any particular way.

We can definitely make everything numbered, though.

**Comment by Jared-Krajewski** [comment]
> I believe it was @xscottxbrownx who wrote these. I can't assume the intention behind choosing hyphens over numbers, but my guess is that it's all intentional. The number ones are sequential steps for people to take, whereas the hyphens just denote specific points that aren't ordered in any particular way.
> 
> We can definitely make everything numbered, though.

your assumption is correct.

**Comment by andycwilliams** [comment]
imo it's fine to leave as is. I would vote for what's most intuitive for each section, rather than ensuring they all use the same thing

**Comment by Jared-Krajewski** [comment]
we can add this one to the discussion at the next in person or maybe tomorrows dev meeting if there is time.

**Comment by nujabes77** [comment]
No discussion. Just change it. It looks inconsistent
