### ISSUE TITLE
Enhancement: fix footer links

### ISSUE THREAD

**Issue by andycwilliams** [codeforpdx/codepdx_website#82]
### Describe the Current Behavior/Feature:

Footer currently does not actual destinations in `socialLinks` section.
codepdx in legalLinks goes to website url, it should scroll to top of home page.

---

### Proposed Implementation:

- Add proper destination to each link and make sure they are recognized in DOM as links

**Comment by ogorman89** [comment]
Here's my .02

Right now, there are four links in `legalLinks`.

1. About - this should probably link to `Home` since that's the closest thing we have to an `About` page.
2. Code Of Conduct - link to the GitHub CoC that @andycwilliams linked above
3. Contact Us - should trigger the new contact modal @andycwilliams is working on
4. CODE PDX - make this text; I don't think it needs to be a link, especially if it links to the same place as `About`

**Comment by andycwilliams** [comment]
> Here's my .02
> 
> Right now, there are four links in `legalLinks`.
> 
> 1. About - this should probably link to `Home` since that's the closest thing we have to an `About` page.
> 2. Code Of Conduct - link to the GitHub CoC that @andycwilliams linked above
> 3. Contact Us - should trigger the new contact modal @andycwilliams is working on
> 4. CODE PDX - make this text; I don't think it needs to be a link, especially if it links to the same place as `About`

Agreed with all of the above. Only comment is that `About` could link or scroll directly to the About section on the Home page. 

And I would like the code of conduct updated soon but that's outside of this issue.
